language: node_js
node_js:
- '10'
script:
- npm run predeploy
- npm run deploy
notifications:
  email:
    recipients:
    - wenceslauslee@gmail.com
    on_success: change
    on_failure: always
env:
  global:
    - secure: JKne2kQAazUFyRV3buwx2g3x8WdHOEftEIjaUveopv53F84VEBUon6dpj5A/FatrkiXud/Pk6nepNczdVpLKp9Lfuq4Y0XY0ogX12zc4ooNB4qvOUSNcXPmBla0uNHGdMP9hTdimiAGLQZHT/pzMvgh7uc5t7DAVNHPj0aOtI4FIdcpx97S3TkPhuUUSDQXK/4ZohwNnKdURQVRQO6xPAqgNgSdJ+il5P+ikvawpETAK0KfU5X9QJXfGsTLsHfUpqDhh56iDffnDmWzjfg5xgexiN4jj8wRpMR+ZEHSQQMUpI7AJRU9ZRJVINwZmQdWfHlX+me+RjMVBkkDR5OkLabju9nlWPomJCMLUuIOwX2DLb1lIEyaAzOBQAPM4cafsfreZrlvU0aUxa6fYJF9QAh49jsjQiUi6Ffa5f6WIEtVjFqSORlTxUgM42vTGr3Zzfuf7GQP23n6wgI4tncUszvXavcbg4+1aX5kW1VlFv0i3j6QESvX4wPG2h4wdbxTdaFSLDAXOBIl/ex3ZmcqSxLFthh2l42ES6yPGUt/Ptt5YbiMQFlxliidxvHBahdjmVcKkWjh2JP8vrLXbF7Sunx7r3f+8ayUGRqZyp4H1BU5ythB3vcpa4vx6sF+vrSPUsRWEhnw4tQyylRnGw5gDbNUYG8jGalJs9OkvAVpiaPA=
    - secure: wYvCyyxQfCW5PR9YiVx3ookySDWQ5aGCnlQbV9TXmusbIMGXX32zSx3y5r3ea921UauJxA2kIDEOB+Y9sKCVr6JdKER8dEqptMgUexn0u+vncwvllpYWkdi0/8o4F89QdqtHA7OzUWEKH2a0p+YNW2F3taUjNVvJoj8ADhLKrwYeVU7hyqGJrbhLw9UmxjMKyMIAgev+r3E5APebTTiInPb/SEnR+Qb8LrqfFBQCFNuXMaunkzPAMdWdeEcbIaOhV4qrg+eDj9NsAcDBYb4o22gNH0fZDhZca7p2Cuvz2bMAsa5lOxTNLScVKgd3J2/P3YfH3okuw5A9PntfO0xTjPaMjDXrG2noAL/rX0aP9UDN4CR+uWfIp6MKFOpu6R50Q72wwkSRnULa40dWkJyh4tY3FoHfd6pfdmZ2R6Le/y4Dgufp5he5I8S328H8v901uT42Tg4puWUwhoHmBGBxQ8HJDwdgoESF3oJGIwXMEjkjXYzc7a8N7EROggbh8Ly9VvJXV26zbd3IIIIlVd+hxCAsUNIEF9WcBDNhZX2WxOZlnOcfuntTeFSUUPzeP87lxQ43wHuTK7V842+BRd94az9z3j4WiTlaWgK+nXHKUhCyZREDLaNdCbqDfNqVmRRtZyEkzTrxJIdsZDSb9f+lyY+49YTuHt/W3G3Xaku9utI=
